spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  resource:
    add-mappings: true
  datasource:
    url: jdbc:mysql://localhost:3306/dbtest?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a333